### ISSUE TITLE
Problem with docsify-embed-pdf

### ISSUE THREAD

**Issue by slamino** [jhildenbiddle/docsify-themeable#11]
Is this plugin compatible with docsify-themeable, or am I missing something ? 

Uncaught TypeError: Cannot read property 'localeCompare' of undefined
    at pdf_renderer (docsify-pdf-embed.js:22)

my index file:
[index.html.txt](https://github.com/jhildenbiddle/docsify-themeable/files/2791222/index.html.txt)

Thanks in advance.

**Comment by jhildenbiddle** [comment]
Works without issue in this demo:

* Demo: https://m47xmj9lnx.codesandbox.io/
* Editor: https://codesandbox.io/s/m47xmj9lnx

**Note:** Due to the way codesandbox.io sandboxes the editor and preview windows, the demo will only work when the preview is launched as a separate window. This is a codesandbox issue and not a docsify, docisfy-themeable, or plugin issue.

The error indicates that the issue is with `docsify-pdf-embed.js` and its attempt use of a `localCompare` property that doesn't exist. I'm guessing this is an attempt to use [String.prototype.localeCompare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) which may be failing due to lack of [browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Browser_compatibility).

You also have a few issues with your `<script>` tags:

```html
<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/docsify@4"></script>
<script src="//unpkg.com/docsify/lib/plugins/zoom-image.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/docsify-tabs@1"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/pdfobject/2.1.1/pdfobject.min.js"></script> 
<script src="ressources/js/docsify-pdf-embed.js"></script>
```

1. docisfy is loaded twice (first two `<script>` tags)
1. docsify-themeable `<script>` tag is not included (see [docs](https://jhildenbiddle.github.io/docsify-themeable/#/quick-start))
1. Versions are only specified for some files
1. Sources (unpkg/cdnjs/local) and formatting (`//` vs `https://`) are all over the place.

Here's is what I would suggest instead:

```html
<script src="https://cdn.jsdelivr.net/npm/docsify@4"></script>
<script src="https://cdn.jsdelivr.net/npm/docsify-themeable@0"></script>
<script src="https://cdn.jsdelivr.net/npm/docsify-tabs@1"></script>
<script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/zoom-image.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pdfobject@2"></script>
<script src="https://cdn.jsdelivr.net/npm/docsify-pdf-embed-plugin@1"></script>
```
