### ISSUE TITLE
Hide sidebar on a large screen

### ISSUE THREAD

**Issue by shawntabrizi** [jhildenbiddle/docsify-themeable#13]
The sidebar toggle appears to be disabled when the screen is large (even though it still shows on the screen).

Why not enable the button so that it can still be clicked, even on a large screen? I thought it was broken until I realized this behavior.

**Comment by jhildenbiddle** [comment]
Fixed in 0.6.3.

FYI -- jsDelivr takes a little longer to update the version-based URLs (i.e. the ones ending in `@[verson]` than the previous CDN (unpkg.com) due to how they cache files on the client. If you're using the recommended CDN link (ending in `@0`), you likely won't see the fixed behavior for 12-24 hours. You can always force the update by specifying versions (e.g. `@0.6.3`) in your jsDelivr URLs, but doing so means you won't automatically pick up minor/patch versions (which means new features/bug fixes) when they are released.

Thanks for filing the issue, @shawntabrizi. Much appreciated.
