### ISSUE TITLE
high CPU usage https://jhildenbiddle.github.io/docsify-themeable/

### ISSUE THREAD

**Issue by 2p4g0** [jhildenbiddle/docsify-themeable#2]
<img width="993" alt="screen shot 2018-06-22 at 4 15 46 pm" src="https://user-images.githubusercontent.com/39396571/41778687-2fbd3c2a-7638-11e8-84e3-39a4b24bac5c.png">

docsify-themeable js script is the cause of this. 

Any way I can fix this?

**Comment by jhildenbiddle** [comment]
HI @2p4g0.

Happy to help, but I'll need a little more to work with than just an Activity Monitor screenshot.

* What browser(s) / OS are you seeing this behavior with? 
* Do you have any browser extensions installed?

Thanks for creating the issue, @2p4g0. Hope to get this resolved quickly.

**Comment by 2p4g0** [comment]
macOS 10.13.3 High Sierra / Safari Version 11.0.3 (13604.5.6)
No any extensions installed. 

Everything works smooth in Firefox and Chrome, this only happens in Safari. I also checked it in Safari Technology Preview, loads cpu 100%. So this is definitely a Safari-related bug.

**Comment by jhildenbiddle** [comment]
Great catch, @2p4g0.

Turns out Safari didn't like the combination of a background image and `transition: all` on the search field. Removing the transition (which wasn't being used anyway) solved the issue.

![safari cpu](https://user-images.githubusercontent.com/442527/41807020-3b8ba240-767d-11e8-87cc-652e1320a17b.jpg)

The fix is in 0.1.2, which I published tonight. Assuming you're linking to the latest version on unpkg.com (as listed in the docs) you should pick up the fix automatically.

Thanks for taking the time to report it. Very much appreciated!
