### ISSUE TITLE
Themes src not packaged in npm

### ISSUE THREAD

**Issue by jackbentley** [jhildenbiddle/docsify-themeable#26]
I'm trying to create my own theme(s) in SCSS that extend the basic themes in the repo. The problem is, after `npm install`ing this package, the source for the themes are nowhere to be seen!

https://github.com/jhildenbiddle/docsify-themeable/blob/master/package.json#L33

**Comment by jhildenbiddle** [comment]
Hey @jackbentley,

The source files used to build the default docsify-themeable themes aren't included in the npm package, but they are available here in the GitHub repo. 

To be honest, I hadn't considered other devs leveraging the source SCSS, but I do understand how this can be useful for generating a separate custom theme as a standalone file. I can add these easily enough by including the `/src/scss` directory instead of just `src/scss/themes/defaults`.

Let me know if you're still interested in this change and I can push a new version. Thx!

**Comment by jhildenbiddle** [comment]
Hey @jackbentley --

Been a while, but I wanted to let you know that I have made the change as requested. The scss source files will be included as part of the npm package with the next release.
