### ISSUE TITLE
A way to make non-link sidebar menu items collapsible?

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#27]
I have a _sidebar.md with some root-level items that aren't links, and the sub-items are pages (rather than subsections).

```md
-   Getting Started

    -   [Install](install.md)
    -   [Workflows](workflows.md)

-   Examples

    -   [Hello 3D](examples/hello3d.md)
    -   [Morphing Spiral](examples/spiral.md)
```

Here's what it looks like:

<img width="293" alt="Screen Shot 2019-08-12 at 9 55 01 PM" src="https://user-images.githubusercontent.com/297678/62916115-d9748600-bd4b-11e9-9f3a-8d303b9fa9c2.png">

Under "Getting Started" and "Examples", those are separate pages.

Then if I click on the "Install" page, for example, the menu shows the sub-sections:

<img width="291" alt="Screen Shot 2019-08-12 at 9 56 56 PM" src="https://user-images.githubusercontent.com/297678/62916170-1e002180-bd4c-11e9-938d-1fd7dfc7a48e.png">

Is there some way to make those root items expandable/collapsible? (The "Getting Started" and "Examples" items)

**Comment by trusktr** [comment]
I think the problem is (with docsify) that Vue code doesn't run in the sidebar. No matter what Vue code I try in `_sidebar.md` it doesn't run.

**Comment by jackbentley** [comment]
This is a thing in Docsify in general. Have a look at this plugin:
https://github.com/iPeng6/docsify-sidebar-collapse

You might want to use my fork though, as it adds a lot of unnecessary CSS for styling:
https://github.com/jackbentley/docsify-sidebar-collapse/tree/feature/css

The built version of my fork is available here:
https://cdn.jsdelivr.net/gh/jackbentley/docsify-sidebar-collapse@build/dist/docsify-sidebar-collapse.min.js

**Comment by jhildenbiddle** [comment]
@trusktr --

As @jackbentley points out, docsify doesn't provide a mechanism to render collapsable non-link menu items out of the box. A plugin is one way to address the issue, but you may also want to consider HTML's native [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) disclosure element:

```markdown
<details>
  <summary>Getting Started</summary>

    -   [Install](install.md)
    -   [Workflows](workflows.md)

</details>

<details>
  <summary>Examples</summary>

    -   [Hello 3D](examples/hello3d.md)
    -   [Morphing Spiral](examples/spiral.md)

</details>
```

This works today w/o plugins with a few  need-to-be-resolved issues:

1. Neither docsify nor docsify-themeable themes provide styling for `<details>` elements in the sidebar by default. You can style these yourself using your own CSS, but ideally that wouldn't be necessary.
1. Both docsify and docsify-themeable auto-close the sidebar menu on small screens as soon as a focusable element (a link, a `<details>` block, etc.) is clicked. This behavior would need to change to allow the details element to toggle open/closed without closing the sidebar on small screens.
1. HTML provides no mechanism to auto-close one `<details>` element when another one is opened. This may or may not be important to you, but I wanted to point it out since this is different than the behavior provided the plugin @jackbentley mentioned above.

If you're interested, I can add the necessary items to the backlog.

**Comment by jhildenbiddle** [comment]
@trusktr, @jackbentley --

I was going to add styles to support `<details>` elements in the sidebar, but the behavior isn't as expected due to the way docsify updates the sidebar. Specifically, docsify lacks the ability to expand `<details>` elements to display the active sidebar link, which leads to confusion both when clicking a link within a `<details>` element (because the `<details>` element collapses when the page content loads) and when navigating to a docsify site via page-specific URL (leaving the users confused about where they are when they land).

For this reason, I'm closing this issue and directing those interested in the behavior you describe to the alternatives mentioned by @jackbentley. Ideally, this functionality would be baked into docsify. If you'd like to see that happen, I suggest creating an issue [within the docsify repo](https://github.com/docsifyjs/docsify/issues).

Thanks!
