### ISSUE TITLE
Table contents can overflow without being scrollable

### ISSUE THREAD

**Issue by difosfor** [jhildenbiddle/docsify-themeable#38]
E.g. see: 
https://docs.liveryvideo.com/web-sdk

Here's how I patched it there with CSS for now:
```
/* Allow docsify-themeable tables to scroll horizontally when necessary */
.markdown-section .table-wrapper {
  overflow-x: auto;
}

/* Prevent docsify-themeable responsive table cells from overflowing (unscrollable) */
@media (max-width: 30em) {
  .markdown-section .table-wrapper td {
    flex-wrap: wrap;
  }
}
```

I think in the case of the responsive table (max-width: 30em) with the ::before being used to repeat the column header that the td contents should be wrapped by a div with word wrapping and hyphens enabled.

**Comment by jhildenbiddle** [comment]
Thanks for filing the issue, @difosfor.

The `overflow-x: auto` fix works without issue. The `flex-wrap: wrap` fix causes content to wrap under the label in responsive tables. I have updated the method of displaying rendering these labels so that this fix is no longer necessary. This will be available in the next version, which will be published soon.
