### ISSUE TITLE
[idea] --search-input-placeholder-color--focus property

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#47]
It seems there is only 	`--search-input-placeholder-color` but not `--search-input-placeholder-color--focus`

**Comment by jhildenbiddle** [comment]
I'm not sure I've ever seen a website change the color of an input field's placeholder text when the field has focus. Not saying it hasn't happened, but it seems like a poor way of indicating focus to users.

Can you share a few links where you've seen this implemented?

**Comment by jhildenbiddle** [comment]
Thank for filing the issue, @trusktr.

I'm closing this for now because after further consideration I don't think an `<input>` field's placeholder text should change when the element has focus. The only application of this property that makes sense to me is to set the placeholder text color to transparent on focus (making the text disappear), and I'm not convinced that's interesting enough be a configurable option.
