### ISSUE TITLE
Allow custom properties for changing font size of inline code blocks in headers.

### ISSUE THREAD

**Issue by UltraInstinct05** [jhildenbiddle/docsify-themeable#56]
# What's the issue about ?
Often times, one needs to explain about certain function or modules in a given header section & the said function/module is wrapped in back ticks. However, the wrapping decreases the font size and the heading looks inconsistent.

# Solution
Add custom properties `--heading-h{1-6}-code-font-size` to allow the user to change the font size of header inline code blocks.

**Comment by jhildenbiddle** [comment]
Instead of adding six more theme properties, I think a better solution is to adjust the font size of `<code>` elements inside headings to a size relative to the heading font size. Here is an example after setting these `<code>` element to `font-size: 0.875em` by default:

<img width="403" alt="Screen Shot 2020-10-02 at 11 32 14 AM" src="https://user-images.githubusercontent.com/442527/94947406-34fb5900-04a3-11eb-8110-36286e18154a.png">
