### ISSUE TITLE
Feature request: align navbar on the left

### ISSUE THREAD

**Issue by ropnop** [jhildenbiddle/docsify-themeable#60]
Hello! I would love the ability to toggle the alignment on the top navbar so the links can align left instead of the default right. I believe it would just be a simple change to make [this value](https://github.com/jhildenbiddle/docsify-themeable/blob/master/src/scss/app/_navbar.scss#L9) a variable, but let me know what you think. Happy to submit a PR or test out!

**Comment by jhildenbiddle** [comment]
Hi @ropnop --

This type of feature is better implemented as a [docsify](https://github.com/docsifyjs/docsify/) feature that this theme can then support rather than feature available only to docsify-themeable.

Moving the sidebar is easy enough, but there are other elements that will also need to be adjusted like the sidebar toggle button, the top navigation (if applicable), sliding the content when the sidebar is toggled, etc. For now, the easiest path forward would be to create your own `<style>` block and adjust the CSS values as needed.
