### ISSUE TITLE
Unexpected style of title when I come to the third level of the sidebar

### ISSUE THREAD

**Issue by Joyrocky** [jhildenbiddle/docsify-themeable#75]
When I just set to the third level title in the sidebar.md, the style of the third level title is unexpected. Can you give me some suggestions about this situation?

![image](https://user-images.githubusercontent.com/23481533/179007061-a3d1e430-80be-41e7-8a4f-8733f16cba49.png)
![image](https://user-images.githubusercontent.com/23481533/179007333-6d9138e1-c8b6-457d-9c7c-5a387024c5b1.png)

**Comment by jhildenbiddle** [comment]
Hi @Joyrocky. 

This will be fixed in the upcoming release which should be published by EOD tomorrow.

FWIW, the `-` is inserted by the `theme-simple.css` them for third-level content links in sidebar navigation. This can be controlled by setting the `--sidebar-nav-link-before-content-l3` custom property:

```html
<style>
:root {
  --sidebar-nav-link-before-content-l3: '😀';
}
</style>
```

To fix your issue, you can either wait for the update or set the value to an empty string while you wait:

```html
<style>
:root {
  --sidebar-nav-link-before-content-l3: ;
}
</style>
```
