### ISSUE TITLE
Unexplained 'TypeError: Attempted to assign to readonly property.' console error message

### ISSUE THREAD

**Issue by paulhibbitts** [jhildenbiddle/docsify-themeable#85]
I have recently gotten the Docsify Search Plugin going with Docsify-This.net, and have noticed what looks to be a themeable-related console error messages:
**TypeError: Attempted to assign to readonly property.**
**Uncaught TypeError: Cannot create property 'hideOtherSidebarContent' on string 'true'**

It is specifically related to this Themeable JS line:
`window.$docsify.search.hideOtherSidebarContent = true;`

You should be able to see a live demo of this issue by going to https://paulhibbitts.github.io/docsify-this-search-test/?basePath=https://raw.githubusercontent.com/hibbitts-design/docsify-this-multiple-page-course-site/main&homepage=home.md&sidebar=true&loadSidebar=_sidebar.md&loadNavbar=_navbar.md&search=true and then viewing the console.

As a workaround, I've removed that line from my local Themeable JS but thought I'd post the issue here in case you might see why this is happening.

Thanks very much, and as always I greatly appreciate all of your amazing work with Docsify Themeable!
Paul

**Comment by jhildenbiddle** [comment]
Hi @paulhibbitts,

Thanks for filing the issue. Two things are happening here...

1. docsify-themeable is incorrectly assuming that the `$docsify.search` configuration value will always be either `undefined` or an object. This is a bug. I will address the issue in the next release.
2. docsify-this is setting the `$docsify.search` configuration value incorrectly. Using [this demo](https://paulhibbitts.github.io/docsify-this-search-test/?basePath=https://raw.githubusercontent.com/hibbitts-design/docsify-this-multiple-page-course-site/main&homepage=home.md&sidebar=true&loadSidebar=_sidebar.md&loadNavbar=_navbar.md&search=true#/?id=how-to-plan-conduct-and-summarize-usability-tests) I can see that the value is set to `"true"` (a string) which:
   - I assume is meant to be a boolean (boolean `true` vs string `"true"` -- notice the quotes) 
   - isn't a valid configuration docsify option according to the [plugin documentation](https://docsify.js.org/#/plugins?id=full-text-search) but...
   - I assume is used internally by docsify-this to determine if search functionality will be included.

I will address the first item in the next release.

My recommendation for the second item is to avoid using custom values for known docsify configuration properties for docsify-this features, and instead store all docsify-this configuration within a `docsifyThis` configuration property. For example, instead of this:

```js
window.$docsify = {
  search: true, // docsify: invalid, docsify-this: Include search plugin
};
```

Do this:

```js
window.$docsify = {
  search: {
    // Standard docisfy search config goes here...
  },
  docsifyThis: {
    includePlugins: [
      'search' // Include search plugin for docsify-this sites
    ]
  }
};
```

FWIW, the `window.$docsify.sidebar` configuration value is also a string of `"true"` which I assume is meant to be a boolean (`true`).

![CleanShot 2023-10-16 at 12 05 40@2x](https://github.com/jhildenbiddle/docsify-themeable/assets/442527/e8921eee-a02b-46c7-831d-0ee81a07e083)

**Comment by paulhibbitts** [comment]
Just seeing this now, thanks so much for looking into this @jhildenbiddle! I appreciate you planning to address item 1 in your next release.

Re: item 2, you've caught a bigger issue for Docsify-This, and that was the passing non-Boolean values for not just Search but other things as well which then set Docsify configs. I've now added code to transform any passed true/false values to true Boolean:

```
    // Convert to Boolean if true or false, otherwise return original value
    function convertToBoolean(value) {
      if (value === 'true') {
        return true;
      } else if (value === 'false') {
        return false;
      } else {
        return value;
      }
    }
 ```

Thanks again!
Paul

**Comment by paulhibbitts** [comment]
That view of variables looks super helpful @jhildenbiddle , could you please tell me how I can access that too?

Thanks again,
Paul

**Comment by eljeffeg** [comment]
Just wanted to add that I'm getting a similar error.
```
docsify-themeable.min.js:8 Uncaught TypeError: Cannot create property 'hideOtherSidebarContent' on string 'auto'
    at docsify-themeable.min.js:8:27945
    at docsify-themeable.min.js:8:28209
```
`window.$docsify.search.hideOtherSidebarContent = !0`

**Comment by jhildenbiddle** [comment]
Thanks, @eljeffeg. 

This issue will be addressed in the next release, but I am waiting on a [few Docsify PRs](https://github.com/docsifyjs/docsify/pulls/jhildenbiddle) to be approved and merged before that happens.

In the meantime, the quick fix is to remove the `search: "auto"` from your docsify configuration. The default `search` value is `"auto"`, so so removing it should not affect the search plugin behavior). This will allow docsify-themeable to set the `hideOtherSidebarContent` properly.

**Comment by jhildenbiddle** [comment]
@paulhibbitts --

> That view of variables looks super helpful @jhildenbiddle , could you please tell me how I can access that too?

Of course! The docsfy configuration and other global variables can be accessed via the JavaScript console (which is part of the developer tools) available in [Chrome](https://developer.chrome.com/docs/devtools/), [Edge](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview), [Firefox](https://firefox-source-docs.mozilla.org/devtools-user/), [Safari](https://support.apple.com/en-il/guide/safari/sfri20948/mac), or any modern browser. The screenshot I provided was taken with Safari 17, but they all function more-or-less the same way.

Once you have the developer tools open, click on the "Console" tab, then type in the following:

```js
window.$docsify
```

This will log the docsify configuration object to the console as shown in the screenshot.

**Comment by paulhibbitts** [comment]
Awesome, that is such a great tip @jhildenbiddle - thank you! I've got it going with no problem 🙂 I've now also been able to verify using this approach that I am indeed setting true/false Docsify variables correctly!

**Comment by jhildenbiddle** [comment]
This issue has been fixed in commit https://github.com/jhildenbiddle/docsify-themeable/commit/88cff66390ad3a62bc5cdc4855af8b372c9e9758 on the `dev` branch.
